#build
FROM node:18.15.0-slim as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

COPY --from=builder --chown=nextjs:nodejs app/.next ./.next
COPY /app/node_modules ./node_modules
COPY /app/package.json ./package.json

USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "start"]
