#build
FROM node:18.15.0-slim as build

WORKDIR /app


COPY package*.json ./

RUN npm install --force


COPY . .

RUN npm run build


FROM node:18.15.0-slim


# copy from build image
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/public ./public


COPY --from=build --chown=nextjs:nodejs app/.next ./.next


USER nextjs

EXPOSE 3000

ENV PORT 3000

CMD ["npm", "run", "start"]
