apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: samuelrcabral/codelivery_frontend:latest
          ports:
            - containerPort: 80
      volumes:
        - name: frontend-volume
          configMap:
            name: frontend-config
            items:
              - key: env
                path: .env.local

